// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9gxS2NfjfYDAEQBej31e3m22vykin1Y',
    appId: '1:482284518295:web:a2c6ab362e2fc87a01a2d2',
    messagingSenderId: '482284518295',
    projectId: 'ksij-kinshasa',
    authDomain: 'ksij-kinshasa.firebaseapp.com',
    storageBucket: 'ksij-kinshasa.appspot.com',
    measurementId: 'G-SZEZXM1CKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCozAHyXC2Of4DS58fYExLmPG5ldWeg3-c',
    appId: '1:482284518295:android:dad94b25dd621b9001a2d2',
    messagingSenderId: '482284518295',
    projectId: 'ksij-kinshasa',
    storageBucket: 'ksij-kinshasa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKsHUNA_2Vx7258vwlvuI-ha06C6jEvl4',
    appId: '1:482284518295:ios:bfc23a86a0d16dbb01a2d2',
    messagingSenderId: '482284518295',
    projectId: 'ksij-kinshasa',
    storageBucket: 'ksij-kinshasa.appspot.com',
    iosBundleId: 'com.test.ksijKinshasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKsHUNA_2Vx7258vwlvuI-ha06C6jEvl4',
    appId: '1:482284518295:ios:40e8182d675bc4bb01a2d2',
    messagingSenderId: '482284518295',
    projectId: 'ksij-kinshasa',
    storageBucket: 'ksij-kinshasa.appspot.com',
    iosBundleId: 'com.example.ksijKinshasa.RunnerTests',
  );
}
